#define	BRK$C_DEVICE	1
#define	BRK$C_USERNAME	2
#define	BRK$C_ALLUSERS	3
#define	BRK$C_ALLTERMS	4
#define	BRK$C_MAXSENDTYPE	4
#define	BRK$C_GENERAL	0
#define	BRK$C_PHONE	1
#define	BRK$C_MAIL	2
#define	BRK$C_QUEUE	3
#define	BRK$C_SHUTDOWN	4
#define	BRK$C_URGENT	5
#define	BRK$C_DCL	6
#define	BRK$C_OPCOM	7
#define	BRK$C_USER1	32
#define	BRK$C_USER2	33
#define	BRK$C_USER3	34
#define	BRK$C_USER4	35
#define	BRK$C_USER5	36
#define	BRK$C_USER6	37
#define	BRK$C_USER7	38
#define	BRK$C_USER8	39
#define	BRK$C_USER9	40
#define	BRK$C_USER10	41
#define	BRK$C_USER11	42
#define	BRK$C_USER12	43
#define	BRK$C_USER13	44
#define	BRK$C_USER14	45
#define	BRK$C_USER15	46
#define	BRK$C_USER16	47
#define	BRK$M_SCREEN	256
#define	BRK$M_BOTTOM	512
#define	BRK$M_NOREFRESH	1024
#define	BRK$M_CLUSTER	2048
#define	BRK$V_SCREEN	8
#define	BRK$V_BOTTOM	9
#define	BRK$V_NOREFRESH	10
#define	BRK$V_CLUSTER	11
