$!  LINK.COM
$ LINK/NOMAP MAIN,VMS,VMS_IO,io,protocol,FILE_QUEUE,headers,bcb_crc,send_file,-
  RECV_FILE,VMS_SEARCH_ROUTE,util,NMR,VMS_TCP,VMS_DECNET,READ_CONFIG,-
  GONE_SERVER,CLUSTER_SERVER, -
  SYS$INPUT:/OPTION
SYS$SHARE:VAXCRTL/SHARE
$!
$ LINK/EXE=[EXE]YGONE YGONE,[MAILER_SRC.BMAIL]MAIL_CHECK, -
  SYS$INPUT:/OPTION
SYS$SHARE:VAXCRTL/SHARE
$!
$ WRITE SYS$OUTPUT "Executable in MAIN.EXE in the sources directory"
$ EXIT
