#!/bin/sh
#
#  By Paul Bryant <P.Bryant@rl.ac.uk>
#
MFLOG=/usr/tmp/maketable.log
rm $MFLOG
echo start maketable >> $MFLOG
TMPFILE=/usr/tmp/maketable.tmp
TMPFILE1=/usr/tmp/maketablex.tmp
TMPFILE2=/usr/tmp/maketabley.tmp
rm $TMPFILE
rm $TMPFILE1
rm $TMPFILE2
/usr/local/nje/bin/receive -a -o $TMPFILE $1
rc=$?
if [ $rc != 0 ]; then
     echo "receive failed" >> $MFLOG
     exit $rc
fi
/usr/local/nje/huji/namesfilter -zmailer < $TMPFILE | sort > $TMPFILE2 
/newsendmail/makemap/makemap dbm /etc/bitnettable < $TMPFILE2
rc=$?
if [ $rc != 0 ]; then
     echo "namesfiilter failed" >> $MFLOG
     exit $rc
fi
/usr/local/nje/paroute/paroute -l $2 -k /usr/local/nje/paroute/paroute.conf $TMPFILE > $TMPFILE1
/usr/local/nje/huji/njeroutes /usr/local/nje/huji/huji_nje.header $TMPFILE1 /usr/local/nje/huji/huji_nje.route  >> $MFLOG
rc=$?
if [ $rc != 0 ]; then
      echo "njeroutes failed" $rc  >> $MFLOG
      exit $rc
fi
rm $TMPFILE
rm $TMPFILE1
rm $TMPFILE2
echo "end maketable" >> $MFLOG 
